# fly.toml app configuration file generated for twitter-moon on 2023-12-25T07:01:06+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "twitter-moon"
primary_region = "sin"

[build]

[[mounts]]
  source = "img"
  destination = "/data"
  initial_size = "1"
  auto_extend_size_threshold = 0

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
